const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {spawn}=require('node:child_process');const {io}=require('socket.io-client');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function event(s,name,trigger){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{s.off(name,fn);reject(Error('Timeout '+name));},6000);const fn=d=>{clearTimeout(timer);s.off(name,fn);resolve(d);};s.on(name,fn);trigger?.();});}
const ack=(s,n,d)=>new Promise((resolve,reject)=>s.timeout(5000).emit(n,d,(e,r)=>e?reject(e):resolve(r)));
test('3.5.0 : sondages persistants, messages vocaux, permissions et MP privés',{timeout:45000},async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'docspace-features-'));const root=path.resolve(__dirname,'..');const port=32000+Math.floor(Math.random()*6000);const url='http://127.0.0.1:'+port;const clients=[];let proc;let logs='';
 async function start(){proc=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,PORT:String(port),HOST:'127.0.0.1',DATA_DIR:path.join(dir,'data'),UPLOAD_DIR:path.join(dir,'uploads'),ADMIN_PASSWORD:'TEST-ADMIN-ONLY',FIREBASE_CREDENTIALS:''},stdio:['ignore','pipe','pipe']});proc.stdout.on('data',d=>logs+=d);proc.stderr.on('data',d=>logs+=d);for(let i=0;i<100;i++){try{if((await fetch(url+'/health-lite')).ok)return;}catch{}await delay(40);}throw Error('Server failed '+logs.slice(-1000));}
 async function stop(){if(!proc||proc.exitCode!==null)return;const end=new Promise(r=>proc.once('exit',r));proc.kill('SIGTERM');await end;}
 async function client(name,register=true){const s=io(url,{transports:['websocket'],autoConnect:false,forceNew:true});clients.push(s);await event(s,'connect',()=>s.connect());const data=await event(s,register?'account_registered':'account_logged_in',()=>s.emit(register?'register_account':'login_account',{username:name,password:'Test-Password-123'}));await event(s,'user_join_ready',()=>s.emit('user_join',{username:name,deviceId:name+Math.random()}));s.token=data.token;return s;}
 t.after(async()=>{clients.forEach(s=>s.disconnect());await stop();fs.rmSync(dir,{recursive:true,force:true});});await start();let a=await client('Alice'),b=await client('Bob'),c=await client('Chloe');let privatePoll,publicPoll,voiceMessage;
 await t.test('Tous les thèmes et effets sont accessibles au premier niveau',async()=>{const xp=await event(a,'xp_data',()=>a.emit('get_xp'));assert(Object.values(xp.themeUnlocks).every(Boolean));assert.equal(xp.customThemeUnlocked,true);const saved=await event(a,'xp_data',()=>a.emit('set_name_effect',{effect:'name_neon'}));assert.equal(saved.activeNameEffect,'name_neon');});
 await t.test('Un mot de passe admin vide ou un autre pseudo ne donne aucun droit',async()=>{assert.equal((await event(c,'admin_login_result',()=>c.emit('admin_login',{username:'Alice',password:'TEST-ADMIN-ONLY'}))).success,false);assert.equal((await ack(c,'admin_snapshot',{})).success,false);assert.equal((await event(a,'admin_login_result',()=>a.emit('admin_login',{username:'Alice',password:'TEST-ADMIN-ONLY'}))).success,true);assert.equal((await ack(a,'admin_snapshot',{})).success,true);});
 await t.test('Sondage MP : audience limitée aux deux personnes et vote validé',async()=>{
  let leaked=0;const watch=()=>leaked++;c.on('poll_update',watch);c.on('dm_received',watch);
  const invalid=await ack(a,'create_poll',{to:'Bob',question:'Test ?',options:['Unique']});assert.equal(invalid.success,false);
  const result=await ack(a,'create_poll',{to:'Bob',question:'On joue quand ?',options:['Ce soir','Demain']});assert.equal(result.success,true);privatePoll=result.poll.id;
  const votes=await ack(b,'vote_poll',{pollId:privatePoll,optionIndex:0});assert.equal(votes.poll.options[0].votes,1);
  const change=await ack(b,'vote_poll',{pollId:privatePoll,optionIndex:1});assert.equal(change.poll.options[0].votes,0);assert.equal(change.poll.options[1].votes,1);
  assert.equal((await ack(b,'vote_poll',{pollId:privatePoll,optionIndex:900})).success,false);
  assert.equal((await ack(c,'vote_poll',{pollId:privatePoll,optionIndex:0})).success,false);
  assert.equal((await ack(c,'close_poll',{pollId:privatePoll})).success,false);
  const hidden=await ack(c,'get_polls',{to:'Alice'});assert(!hidden.polls.some(p=>p.id===privatePoll));await delay(60);assert.equal(leaked,0);c.off('poll_update',watch);c.off('dm_received',watch);
 });
 await t.test('Sondage de salon : création, changement de vote et clôture',async()=>{const p=await ack(b,'create_poll',{channel:'général',question:'Notre prochaine activité ?',options:['Travail','Arcade']});assert.equal(p.success,true);publicPoll=p.poll.id;assert.equal((await ack(c,'vote_poll',{pollId:publicPoll,optionIndex:1})).success,true);assert.equal((await ack(c,'close_poll',{pollId:publicPoll})).success,false);assert.equal((await ack(b,'close_poll',{pollId:publicPoll})).success,true);assert.equal((await ack(c,'vote_poll',{pollId:publicPoll,optionIndex:0})).success,false);});
 await t.test('Vocal : upload audio, lecture HTTP, envoi privé et métadonnées conservées',async()=>{const body=new FormData();body.append('file',new Blob([Buffer.from('RIFF-test-audio')],{type:'audio/wav'}),'vocal.wav');const r=await fetch(url+'/upload',{method:'POST',headers:{Authorization:'Bearer '+a.token},body});assert.equal(r.status,200);const attachment=await r.json();const sent=await ack(a,'send_dm',{to:'Bob',content:'',attachment:{...attachment,isVoiceClip:true,duration:17}});assert.equal(sent.success,true);voiceMessage=sent.message;assert.equal(voiceMessage.attachment.isVoiceClip,true);assert.equal(voiceMessage.attachment.duration,17);assert.equal(await(await fetch(url+attachment.path)).text(),'RIFF-test-audio');assert.equal((await ack(a,'send_dm',{to:'Bob',content:'',attachment:{path:'/uploads/../../server.js'}})).success,false);});
 await t.test('MP : réactions, modification, épingle, accusé de lecture et suppression contrôlés',async()=>{const m=(await ack(a,'send_dm',{to:'Bob',content:'Message original'})).message;assert.equal((await ack(b,'message_action',{to:'Alice',id:m.id,action:'edit',content:'Faux'})).success,false);assert.equal((await ack(c,'message_action',{to:'Alice',id:m.id,action:'delete'})).success,false);
  assert.equal((await ack(a,'message_action',{to:'Bob',id:m.id,action:'edit',content:'Modifié'})).success,true);assert.equal((await ack(b,'message_action',{to:'Alice',id:m.id,action:'react',emoji:'🔥'})).success,true);assert.equal((await ack(b,'message_action',{to:'Alice',id:m.id,action:'pin'})).success,true);
  const history=await event(b,'dm_history',()=>b.emit('get_dm_history',{username:'Alice'}));const changed=history.messages.find(x=>x.id===m.id);assert.equal(changed.content,'Modifié');assert.deepEqual(changed.reactions['🔥'],['Bob']);assert.equal(changed.pinned,true);
  const read=await event(a,'dm_read',()=>b.emit('mark_dm_read',{username:'Alice',messageId:m.id}));assert.equal(read.username,'Bob');assert(read.readAt>0);
  assert.equal((await ack(b,'message_action',{to:'Alice',id:m.id,action:'delete'})).success,false);assert.equal((await ack(a,'message_action',{to:'Bob',id:m.id,action:'delete'})).success,true);
  const after=await event(b,'dm_history',()=>b.emit('get_dm_history',{username:'Alice'}));assert(!after.messages.some(x=>x.id===m.id));
 });
 await t.test('Après redémarrage : votes, sondages fermés, fichiers vocaux et historique reviennent',async()=>{clients.forEach(s=>s.disconnect());await stop();await start();a=await client('Alice',false);b=await client('Bob',false);const p=await ack(a,'get_polls',{to:'Bob'});assert.equal(p.polls.find(x=>x.id===privatePoll).options[1].votes,1);const publicData=await ack(b,'get_polls',{channel:'général'});assert.equal(publicData.polls.find(x=>x.id===publicPoll).closed,true);const d=await event(b,'dm_history',()=>b.emit('get_dm_history',{username:'Alice'}));assert(d.messages.some(x=>x.id===voiceMessage.id&&x.attachment.isVoiceClip));assert.equal((await ack(a,'admin_snapshot',{})).success,false);});
});
