const {test}=require('node:test');const assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');const {spawn}=require('node:child_process');const {io}=require('socket.io-client');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function event(s,name,trigger){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{s.off(name,fn);reject(Error('Timeout '+name));},5000);function fn(d){clearTimeout(timer);s.off(name,fn);resolve(d);}s.on(name,fn);trigger?.();});}
const ack=(s,name,data)=>new Promise((resolve,reject)=>s.timeout(5000).emit(name,data,(e,r)=>e?reject(e):resolve(r)));
test('3.5.1 : invitations, Pong en ligne, avatars et catalogue',{timeout:30000},async t=>{
 const root=path.resolve(__dirname,'..'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'docspace351-')),port=39000+Math.floor(Math.random()*4000),url='http://127.0.0.1:'+port;const clients=[];let proc,logs='';
 async function start(){proc=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,PORT:String(port),HOST:'127.0.0.1',DATA_DIR:path.join(dir,'data'),UPLOAD_DIR:path.join(dir,'uploads'),FIREBASE_CREDENTIALS:'',GIPHY_API_KEY:'',YOUTUBE_API_KEY:''},stdio:['ignore','pipe','pipe']});proc.stdout.on('data',d=>logs+=d);proc.stderr.on('data',d=>logs+=d);for(let i=0;i<100;i++){try{if((await fetch(url+'/health-lite')).ok)return;}catch{}await delay(30);}throw Error(logs.slice(-1500));}
 async function stop(){if(proc?.exitCode===null){const end=new Promise(r=>proc.once('exit',r));proc.kill('SIGTERM');await end;}}
 async function client(name,register=true){const s=io(url,{transports:['websocket'],autoConnect:false,forceNew:true});clients.push(s);await event(s,'connect',()=>s.connect());const data=await event(s,register?'account_registered':'account_logged_in',()=>s.emit(register?'register_account':'login_account',{username:name,password:'Test-Password-123'}));s.token=data.token;await event(s,'user_join_ready',()=>s.emit('user_join',{username:name,deviceId:name+Math.random()}));return s;}
 t.after(async()=>{clients.forEach(s=>s.disconnect());await stop();fs.rmSync(dir,{recursive:true,force:true});});await start();let a=await client('Alice351'),b=await client('Bob351'),c=await client('Chloe351');
 await t.test('Durées et sélection GIPHY disponibles sans clé externe',async()=>{const stats=await(await fetch(url+'/api/stats')).json();assert.equal(stats.serverVersion,'3.5.1');assert.equal(typeof stats.uptimeTotalSeconds,'number');assert.equal(typeof stats.uptimeSessionSeconds,'number');assert(!Number.isNaN(Date.parse(stats.sessionStartedAt)));const gifs=await(await fetch(url+'/api/gifs')).json();assert.equal(gifs.source,'GIPHY_SELECTION');assert.equal(gifs.gifs.length,14);for(const g of gifs.gifs){assert.match(g.full,/^https:\/\/media\.giphy\.com\/media\/[a-zA-Z0-9]+\/giphy\.gif$/);assert.equal(g.preview,g.full);}const search=await(await fetch(url+'/api/gifs?q=bravo')).json();assert(search.gifs.length>0);assert(search.gifs.every(g=>g.full.startsWith('https://media.giphy.com/')));const notes=await(await fetch(url+'/patchnotes.json')).json();assert.equal(notes.versions[0].version,'3.5.1');assert.equal((await(await fetch(url+'/api/videos')).json()).configured,false);});
 await t.test('Amitié : demande unique, acceptation et état partagé',async()=>{const incoming=await event(b,'friend_request_received',()=>a.emit('send_friend_request',{username:'bob351'}));assert.equal(incoming.from||incoming.username,'Alice351');const accepted=await event(a,'friend_accepted',()=>b.emit('accept_friend',{username:'Alice351'}));assert.equal(accepted.username,'Bob351');const friends=await event(a,'friends_list',()=>a.emit('get_friends'));assert(friends.friends.some(f=>f.username==='Bob351'));const duplicate=await event(a,'friend_error',()=>a.emit('send_friend_request',{username:'bob351'}));assert.match(duplicate.message,/Déjà amis/i);});
 await t.test('Invitation privée : destinataire seul autorisé à accepter, même code reçu',async()=>{let leaked=0;c.on('game_invite_received',()=>leaked++);c.on('game_invite_start',()=>leaked++);const receive=event(b,'game_invite_received');const result=await ack(a,'game_invite',{to:'bob351',game:'pong'});assert.equal(result.success,true);const v=await receive;assert.equal(v.id,result.invite.id);assert.equal((await ack(c,'game_invite_reply',{id:v.id,accept:true})).success,false);const sa=event(a,'game_invite_start'),sb=event(b,'game_invite_start');assert.equal((await ack(b,'game_invite_reply',{id:v.id,accept:true})).success,true);assert.equal((await sa).code,(await sb).code);assert.equal((await ack(b,'game_invite_reply',{id:v.id,accept:true})).success,false);assert.equal(leaked,0);});
 await t.test('Pong : simulation serveur, limites, deux joueurs et départ propre',async()=>{let latest;const watch=d=>latest=d;b.on('pong_state',watch);assert.equal((await ack(a,'pong_join',{code:'TEST351'})).state.phase,'waiting');assert.equal((await ack(b,'pong_join',{code:'TEST351'})).state.phase,'playing');assert.equal((await ack(c,'pong_join',{code:'TEST351'})).success,false);await ack(a,'pong_move',{code:'TEST351',y:-500});await ack(c,'pong_move',{code:'TEST351',y:.88});await delay(450);assert(latest.paddles[0]>=.12&&latest.paddles[0]<.3);assert.equal(latest.paddles[1],.5);await delay(650);assert.notEqual(latest.ball.x,.5);assert.deepEqual(latest.scores,[0,0]);const left=event(b,'pong_peer_left');await ack(a,'pong_leave',{});await left;assert.equal(latest.phase,'waiting');assert.equal((await ack(c,'pong_join',{code:'TEST351'})).success,true);await ack(b,'pong_leave',{});await ack(c,'pong_leave',{});b.off('pong_state',watch);});
 let avatar;
 await t.test('Photo : upload, propagation publique et chemins invalides refusés',async()=>{const body=new FormData();body.append('file',new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64')],{type:'image/png'}),'avatar.png');const r=await fetch(url+'/upload',{method:'POST',headers:{Authorization:'Bearer '+a.token},body});assert.equal(r.status,200);avatar=(await r.json()).path;const update=event(b,'profile_public_updated');await event(a,'profile_updated',()=>a.emit('update_profile',{avatar}));assert.equal((await update).avatar,avatar);const bad=await event(a,'profile_error',()=>a.emit('update_profile',{avatar:'/uploads/../../server.js'}));assert(bad.message);});
 await t.test('Photo et amitié conservées après redémarrage',async()=>{clients.forEach(s=>s.disconnect());await stop();await start();a=await client('Alice351',false);b=await client('Bob351',false);const profile=await event(b,'user_profile',()=>b.emit('get_user_profile',{username:'Alice351'}));assert.equal(profile.avatar,avatar);assert.equal((await fetch(url+avatar)).status,200);const friends=await event(a,'friends_list',()=>a.emit('get_friends'));assert(friends.friends.some(f=>f.username==='Bob351'));});
});
