const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),path=require('node:path');const {JSDOM,VirtualConsole}=require('jsdom');
const pause=()=>new Promise(r=>setTimeout(r,0));
test('Vocal 3.5.1 : cycle de capture et signalisation simulés, caméra et écran indépendants',async t=>{
 const html=fs.readFileSync(path.join(__dirname,'../public/index.html'),'utf8').replace(/<script[^>]*src=[^>]*><\/script>/g,'');const dom=new JSDOM(html,{url:'http://localhost',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:new VirtualConsole()});const w=dom.window;const handlers=new Map(),emitted=[],captures=[],peers=[];let pendingCamera=null;
 const socket={id:'self',connected:true,on(n,f){if(!handlers.has(n))handlers.set(n,[]);handlers.get(n).push(f);},emit(n,d){emitted.push([n,d]);},async receive(n,d){for(const f of handlers.get(n)||[])await f(d);}};
 class Track{constructor(kind){this.kind=kind;this.enabled=true;this.readyState='live';this.stops=0;}stop(){this.stops++;this.readyState='ended';}}
 class Stream{constructor(tracks=[]){this.tracks=tracks;}getTracks(){return this.tracks;}getAudioTracks(){return this.tracks.filter(t=>t.kind==='audio');}getVideoTracks(){return this.tracks.filter(t=>t.kind==='video');}}
 const media=(kind)=>{const s=new Stream([new Track(kind)]);captures.push(s);return s;};
 class Peer{constructor(){this.ts=[];this.connectionState='new';peers.push(this);}addTransceiver(kind){const t={kind,direction:'sendrecv',sender:{track:null,async replaceTrack(track){this.track=track;}}};this.ts.push(t);return t;}getTransceivers(){return this.ts;}async createOffer(){return {type:'offer',sdp:'mock'};}async createAnswer(){return {type:'answer',sdp:'mock'};}async setLocalDescription(d){this.localDescription=d;}async setRemoteDescription(d){this.remoteDescription=d;if(!this.ts.length)for(const k of ['audio','video','video'])this.addTransceiver(k);}async addIceCandidate(){}close(){this.closed=true;}}
 w.MediaStream=Stream;w.RTCPeerConnection=Peer;w.HTMLMediaElement.prototype.play=async()=>{};w.HTMLMediaElement.prototype.pause=()=>{};w.fetch=async()=>({ok:true,json:async()=>({iceServers:[]})});
 const constraints=[];Object.defineProperty(w.navigator,'mediaDevices',{value:{getUserMedia:async c=>{constraints.push(c);if(c.video&&pendingCamera)return pendingCamera;return media(c.video?'video':'audio');},getDisplayMedia:async c=>{assert.equal(c.audio,false);return media('video');},enumerateDevices:async()=>[{kind:'videoinput',deviceId:'cam-a',label:'Face'},{kind:'videoinput',deviceId:'cam-b',label:'USB'},{kind:'audioinput',deviceId:'mic-a',label:'Micro'}]}});
 const toasts=[],state={ready:true,view:'voice'},preferences={camera:'cam-b'};w.DocSpace={socket,state,preferences,toast:m=>toasts.push(m),esc:s=>String(s),icon:()=>'<svg></svg>',avatarHTML:n=>'<span class="avatar">'+n+'</span>'};
 w.eval(fs.readFileSync(path.join(__dirname,'../public/voice.js'),'utf8'));const voice=w.DocSpaceVoice;t.after(()=>{voice.leave();dom.window.close();});
 await t.test('Connexion micro et négociation des pistes sans activer la caméra',async()=>{await voice.join('Vocal Général');assert.equal(captures.length,1);assert.equal(captures[0].getVideoTracks().length,0);await socket.receive('voice_joined',{room:'Vocal Général',participants:[{socketId:'remote',username:'Bob'}]});assert.equal(peers[0].ts.length,3);assert.equal(peers[0].ts[0].sender.track.kind,'audio');assert.equal(peers[0].ts[1].sender.track,null);assert(emitted.some(([n])=>n==='voice_offer'));});
 let camera,screen;
 await t.test('Caméra choisie, écran simultané et rendu vidéo conservé pendant la parole',async()=>{await voice.setCamera(true);camera=captures.at(-1);assert.equal(constraints.at(-1).video.deviceId.exact,'cam-b');await voice.setScreen(true);screen=captures.at(-1);assert.equal(peers[0].ts[1].sender.track,camera.getVideoTracks()[0]);assert.equal(peers[0].ts[2].sender.track,screen.getVideoTracks()[0]);const users=[{socketId:'self',username:'Alice',video:true,screen:true}];voice.renderPage('Vocal Général',users);assert.equal(w.document.querySelectorAll('#voice-media-grid video').length,2);const first=w.document.querySelector('video');assert.equal(first.srcObject,camera);users[0].speaking=true;voice.renderPage('Vocal Général',users);assert.equal(w.document.querySelector('video'),first);assert(first.closest('.voice-tile').classList.contains('speaking'));assert.equal(w.document.getElementById('voice-camera-device').value,'');await pause();assert.equal(w.document.getElementById('voice-camera-device').value,'cam-b');});
 await t.test('Changement de caméra : ancienne piste arrêtée, écran intact',async()=>{const old=camera;preferences.camera='cam-a';await voice.setCamera(true);camera=captures.at(-1);assert.equal(old.getVideoTracks()[0].stops,1);assert.equal(screen.getVideoTracks()[0].stops,0);assert.equal(peers[0].ts[1].sender.track,camera.getVideoTracks()[0]);});
 await t.test('Un nouveau participant reçoit les captures déjà actives',async()=>{await socket.receive('voice_offer',{fromId:'new-peer',offer:{type:'offer',sdp:'mock'}});const peer=peers.at(-1);assert.equal(peer.ts[1].sender.track,camera.getVideoTracks()[0]);assert.equal(peer.ts[2].sender.track,screen.getVideoTracks()[0]);assert(emitted.some(([n,d])=>n==='voice_answer'&&d.targetId==='new-peer'));});
 await t.test('Arrêt natif du partage : caméra conservée, piste écran retirée',async()=>{screen.getVideoTracks()[0].onended();await pause();assert.equal(voice.snapshot().screen,false);assert.equal(voice.snapshot().camera,true);assert.equal(peers[0].ts[2].sender.track,null);assert.equal(peers[0].ts[1].sender.track,camera.getVideoTracks()[0]);});
 await t.test('Quitter ferme tous les périphériques et toutes les connexions',async()=>{voice.leave();assert.equal(voice.snapshot().room,'');assert.equal(camera.getVideoTracks()[0].stops,1);assert.equal(captures[0].getAudioTracks()[0].stops,1);assert(peers.every(p=>p.closed));});
 await t.test('Permission caméra arrivée après départ : capture immédiatement arrêtée',async()=>{await voice.join('Vocal Général');let resolve;pendingCamera=new Promise(r=>resolve=r);const requested=voice.setCamera(true);voice.leave();const late=media('video');resolve(late);await requested;assert.equal(late.getVideoTracks()[0].stops,1);assert.equal(voice.snapshot().camera,false);assert.equal(voice.snapshot().cameraBusy,false);assert.equal(toasts.length,0);});
});
